# Generated by Django 5.2.4 on 2025-08-26 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_reserva_pagoreserva_itemreserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreserva',
            name='descuento_item',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itemreserva',
            name='subtotal',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='descuento_item',
            field=models.IntegerField(default=0, help_text='Descuento en centavos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento del item'),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='subtotal',
            field=models.IntegerField(help_text='Subtotal en centavos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal del item'),
        ),
        migrations.AlterField(
            model_name='pagoreserva',
            name='monto',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_deposito',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_pendiente',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.IntegerField(default=0, help_text='Descuento en centavos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='porcentaje_descuento',
            field=models.IntegerField(default=0, help_text='Porcentaje de descuento aplicado a la venta (0-10000 para 0-100%)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de descuento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.IntegerField(default=0, help_text='Subtotal en centavos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0, help_text='Total en centavos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
    ]
