# Generated by Django 5.2.4 on 2025-08-23 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_colorproducto_stock_reservado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Material, Dimensiones, Peso, etc.', max_length=100, verbose_name='Nombre de la característica')),
                ('valor', models.TextField(help_text='Ej: Algodón 100%, 30x40cm, 2.5kg, etc.', verbose_name='Valor de la característica')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la característica está visible', verbose_name='Característica activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='productos.producto', verbose_name='Producto asociado')),
            ],
            options={
                'verbose_name': 'Característica de producto',
                'verbose_name_plural': 'Características de productos',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['producto'], name='productos_c_product_2afec9_idx'), models.Index(fields=['nombre'], name='productos_c_nombre_f107df_idx'), models.Index(fields=['activo'], name='productos_c_activo_338a5d_idx')],
                'unique_together': {('producto', 'nombre')},
            },
        ),
    ]
