# Generated by Django 5.2.4 on 2025-08-26 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_auto_20250826_1238'),
        ('productos', '0004_caracteristicaproducto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('usuario', 'sku'), name='unique_producto_usuario_sku'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('usuario', 'slug'), name='unique_producto_usuario_slug'),
        ),
    ]
