# Generated by Django 5.2.4 on 2025-08-26 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_unique_producto_usuario_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(help_text='Costo para cálculo de márgenes (en centavos)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.IntegerField(default=0, help_text='Peso en gramos para cálculo de envío', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (gramos)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(help_text='Precio actual de venta al público (en centavos)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_comparacion',
            field=models.IntegerField(blank=True, help_text='Precio tachado para mostrar descuentos (en centavos, opcional)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio original'),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='precio_extra',
            field=models.IntegerField(default=0, help_text='Se suma al precio base del producto (en centavos)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio adicional'),
        ),
    ]
