# Generated by Django 5.2.4 on 2025-08-22 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(help_text='Nombre que aparecerá en la tienda virtual', max_length=200, verbose_name='Nombre de la tienda')),
                ('slug', models.SlugField(help_text='Identificador único para la URL de la tienda', max_length=220, unique=True, verbose_name='Slug para URL')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción que aparecerá en la página principal', verbose_name='Descripción de la tienda')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tiendas/logos/', verbose_name='Logo de la tienda')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='tiendas/favicons/', verbose_name='Favicon')),
                ('imagen_banner', models.ImageField(blank=True, null=True, upload_to='tiendas/banners/', verbose_name='Imagen de banner principal')),
                ('colores_tema', models.JSONField(default=dict, help_text='Configuración de colores personalizados', verbose_name='Colores del tema')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección física')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL de Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL de Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='URL de Twitter')),
                ('whatsapp', models.CharField(blank=True, help_text='Número con código de país, ej: +573147435305', max_length=20, verbose_name='Número de WhatsApp')),
                ('configuracion_pagos', models.JSONField(default=dict, help_text='Credenciales y configuración de métodos de pago', verbose_name='Configuración de pagos')),
                ('configuracion_envios', models.JSONField(default=dict, help_text='Configuración de métodos y costos de envío', verbose_name='Configuración de envíos')),
                ('meta_titulo', models.CharField(blank=True, help_text='Título para SEO (máx 70 caracteres)', max_length=70, verbose_name='Meta título')),
                ('meta_descripcion', models.TextField(blank=True, help_text='Descripción para SEO (máx 160 caracteres)', max_length=160, verbose_name='Meta descripción')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'En Mantenimiento'), ('suspendida', 'Suspendida')], default='activa', max_length=15, verbose_name='Estado de la tienda')),
                ('plan', models.CharField(choices=[('basico', 'Plan Básico'), ('profesional', 'Plan Profesional'), ('premium', 'Plan Premium'), ('enterprise', 'Plan Enterprise')], default='basico', max_length=15, verbose_name='Plan de la tienda')),
                ('mostrar_precios', models.BooleanField(default=True, help_text='Si se muestran los precios en la tienda', verbose_name='Mostrar precios')),
                ('permitir_compras', models.BooleanField(default=True, help_text='Si se permite realizar compras en la tienda', verbose_name='Permitir compras')),
                ('mostrar_stock', models.BooleanField(default=True, help_text='Si se muestra la disponibilidad de productos', verbose_name='Mostrar stock')),
                ('dominio_personalizado', models.CharField(blank=True, help_text='Dominio propio para la tienda (opcional)', max_length=255, verbose_name='Dominio personalizado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_ultima_actividad', models.DateTimeField(blank=True, null=True, verbose_name='Última actividad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tienda_virtual', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario')),
            ],
            options={
                'verbose_name': 'Tienda Virtual',
                'verbose_name_plural': 'Tiendas Virtuales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos_por_pagina', models.PositiveIntegerField(default=12, verbose_name='Productos por página')),
                ('mostrar_productos_relacionados', models.BooleanField(default=True, verbose_name='Mostrar productos relacionados')),
                ('mostrar_productos_recientes', models.BooleanField(default=True, verbose_name='Mostrar productos recientes')),
                ('mostrar_productos_populares', models.BooleanField(default=True, verbose_name='Mostrar productos populares')),
                ('permitir_comentarios', models.BooleanField(default=False, verbose_name='Permitir comentarios en productos')),
                ('permitir_wishlist', models.BooleanField(default=True, verbose_name='Permitir lista de deseos')),
                ('permitir_comparacion', models.BooleanField(default=True, verbose_name='Permitir comparación de productos')),
                ('notificar_nuevos_pedidos', models.BooleanField(default=True, verbose_name='Notificar nuevos pedidos')),
                ('notificar_stock_bajo', models.BooleanField(default=True, verbose_name='Notificar stock bajo')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='ID de Google Analytics')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='ID de Facebook Pixel')),
                ('captcha_habilitado', models.BooleanField(default=False, verbose_name='CAPTCHA habilitado')),
                ('ssl_forzado', models.BooleanField(default=True, verbose_name='Forzar SSL')),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='tiendas.tiendavirtual', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuraciones de Tiendas',
            },
        ),
        migrations.AddIndex(
            model_name='tiendavirtual',
            index=models.Index(fields=['usuario'], name='tiendas_tie_usuario_afd134_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendavirtual',
            index=models.Index(fields=['slug'], name='tiendas_tie_slug_0f8f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendavirtual',
            index=models.Index(fields=['estado'], name='tiendas_tie_estado_c0a9da_idx'),
        ),
        migrations.AddIndex(
            model_name='tiendavirtual',
            index=models.Index(fields=['plan'], name='tiendas_tie_plan_5709e7_idx'),
        ),
    ]
