# Generated by Django 5.2.4 on 2025-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_userusageplan_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='allow_public_access',
            field=models.BooleanField(default=False, help_text='Permite que los productos y categorías sean accesibles públicamente con API key', verbose_name='Permitir acceso público'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='api_key',
            field=models.CharField(blank=True, help_text='Clave API para acceso público a productos y categorías', max_length=64, null=True, unique=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='public_access_created_at',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se habilitó el acceso público', null=True, verbose_name='Fecha de creación de acceso público'),
        ),
    ]
