# Generated by Django 5.2.4 on 2025-09-25 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_allow_public_access_usuario_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('display_name', models.CharField(max_length=100, verbose_name='Nombre para mostrar')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Límite',
                'verbose_name_plural': 'Categorías de Límites',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Plan')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Plan',
                'verbose_name_plural': 'Plantillas de Planes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plans', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.plantemplate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Plan',
                'verbose_name_plural': 'Asignaciones de Planes',
            },
        ),
        migrations.CreateModel(
            name='PlanTemplateLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('number', 'Número'), ('boolean', 'Sí/No'), ('text', 'Texto'), ('unlimited', 'Ilimitado')], default='number', max_length=20)),
                ('limit_value', models.CharField(max_length=255, verbose_name='Valor del Límite')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Ilimitado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.limitcategory')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='usuarios.plantemplate')),
            ],
            options={
                'verbose_name': 'Límite de Plantilla',
                'verbose_name_plural': 'Límites de Plantillas',
                'unique_together': {('template', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserPlanLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('number', 'Número'), ('boolean', 'Sí/No'), ('text', 'Texto'), ('unlimited', 'Ilimitado')], default='number', max_length=20)),
                ('limit_value', models.CharField(max_length=255, verbose_name='Valor del Límite')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Ilimitado')),
                ('current_usage', models.IntegerField(default=0, verbose_name='Uso Actual')),
                ('reset_period', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual'), ('never', 'Nunca')], default='monthly', max_length=20, verbose_name='Período de Reinicio')),
                ('last_reset', models.DateTimeField(blank=True, null=True, verbose_name='Último Reinicio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.limitcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Límite de Usuario',
                'verbose_name_plural': 'Límites de Usuarios',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
