# Generated by Django 5.2.4 on 2025-08-26 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoriaproducto_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categoriaproducto',
            constraint=models.UniqueConstraint(fields=('usuario', 'slug'), name='unique_categoria_usuario_slug'),
        ),
    ]
