# Generated by Django 5.2.4 on 2025-08-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_categoriaproducto_unique_categoria_usuario_slug'),
    ]

    operations = [
    ]
