# Generated by Django 5.2.4 on 2025-09-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_auto_20250826_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categoría padre para crear subcategorías', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='categorias.categoriaproducto', verbose_name='Categoría padre'),
        ),
    ]
