# Generated by Django 5.2.4 on 2025-09-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_categoriaproducto_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaproducto',
            name='parent',
        ),
    ]
