# Generated by Django 5.2.4 on 2025-09-22 19:11

import cors_management.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CORSDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Dominio permitido para CORS (ej: https://example.com, localhost:3000)', max_length=255, unique=True, validators=[cors_management.models.validate_domain_format])),
                ('description', models.TextField(blank=True, help_text='Descripción del propósito de este dominio')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('pending', 'Pendiente de aprobación')], default='pending', help_text='Estado actual del dominio', max_length=20)),
                ('environment', models.CharField(choices=[('development', 'Desarrollo'), ('staging', 'Staging'), ('production', 'Producción'), ('all', 'Todos los entornos')], default='development', help_text='Entorno donde se aplicará este dominio', max_length=20)),
                ('allow_credentials', models.BooleanField(default=False, help_text='Permitir envío de credenciales (cookies, headers de autorización)')),
                ('allowed_methods', models.CharField(default='GET,POST,PUT,DELETE,OPTIONS', help_text='Métodos HTTP permitidos (separados por comas)', max_length=200)),
                ('allowed_headers', models.TextField(default='Accept,Authorization,Content-Type,X-Requested-With', help_text='Headers permitidos (separados por comas)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Fecha y hora de aprobación', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del dominio (opcional)', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Número de veces que se ha usado este dominio')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Última vez que se usó este dominio', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Usuario que aprobó este dominio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cors_domains_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Usuario que creó este dominio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cors_domains_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Usuario que realizó la última modificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cors_domains_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dominio CORS',
                'verbose_name_plural': 'Dominios CORS',
                'db_table': 'cors_domains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CORSDomainAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='Nombre del dominio (guardado para referencia)', max_length=255)),
                ('action', models.CharField(choices=[('create', 'Creado'), ('update', 'Actualizado'), ('delete', 'Eliminado'), ('activate', 'Activado'), ('deactivate', 'Desactivado'), ('approve', 'Aprobado'), ('reject', 'Rechazado')], help_text='Acción realizada', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador')),
                ('changes', models.JSONField(default=dict, help_text='Detalles de los cambios realizados')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la acción')),
                ('cors_domain', models.ForeignKey(help_text='Dominio CORS relacionado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='cors_management.corsdomain')),
                ('user', models.ForeignKey(help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría CORS',
                'verbose_name_plural': 'Logs de Auditoría CORS',
                'db_table': 'cors_domain_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='corsdomain',
            index=models.Index(fields=['domain'], name='cors_domain_domain_8befc6_idx'),
        ),
        migrations.AddIndex(
            model_name='corsdomain',
            index=models.Index(fields=['status'], name='cors_domain_status_363356_idx'),
        ),
        migrations.AddIndex(
            model_name='corsdomain',
            index=models.Index(fields=['environment'], name='cors_domain_environ_63bba6_idx'),
        ),
        migrations.AddIndex(
            model_name='corsdomain',
            index=models.Index(fields=['created_at'], name='cors_domain_created_8cc92f_idx'),
        ),
        migrations.AddIndex(
            model_name='corsdomainauditlog',
            index=models.Index(fields=['domain_name'], name='cors_domain_domain__fb146c_idx'),
        ),
        migrations.AddIndex(
            model_name='corsdomainauditlog',
            index=models.Index(fields=['action'], name='cors_domain_action_2f9c04_idx'),
        ),
        migrations.AddIndex(
            model_name='corsdomainauditlog',
            index=models.Index(fields=['timestamp'], name='cors_domain_timesta_54a182_idx'),
        ),
        migrations.AddIndex(
            model_name='corsdomainauditlog',
            index=models.Index(fields=['user'], name='cors_domain_user_id_d9b8bd_idx'),
        ),
    ]
